/**
 *                          EE 599 Final Project
 *                  Yao Guo, Yang Zhang and Weichang Wang
 *
 * A Cambricon ISA compiler which reads a low-level IR file generated by a neural
 * network program. The low-level IR is optimized by Glow compiler to perform
 * fast training process. This Cambricon compiler further compiles IR to Cambricon
 * ISA which support several useful machine learning instructions. The ISA file
 * can be apply to the Cambricon hardware to perform a hardware-accelerated
 * machine learning process.
 *
 */

#include <iostream>
#include <fstream>

using namespace std;

int main(int argc, char *argv[]) {
    // Check command line arguments
    if (argc != 3) {
        cerr << "Usage: ./executable <input> <output>" << endl;
        return -1;
    }

    // Read input file
    ifstream inFile;
    inFile.open(argv[1]);
    if (!inFile) {
        cerr << "Failed to open file " << argv[1] << endl;
        return -1;
    }

    return 0;
}